### ISSUE TITLE
pyvenv 

### ISSUE THREAD

**Issue by dav2712** [flightaware/piaware_builder#15]
pyvenv seems missing on Ubuntu/Debian/Kali

but python3-venv is correclty installed.

> make[2]: Leaving directory '/home/xxx/Desktop/flightaware/piaware_builder/package-buster/dump1090'
> pyvenv /home/xxx/Desktop/flightaware/piaware_builder/package-buster/debian/venv --without-pip
> make[1]: pyvenv: Command not found
> make[1]: *** [debian/rules:61: setup_venv] Error 127
> make[1]: Leaving directory '/home/xxx/Desktop/flightaware/piaware_builder/package-buster'
> make: *** [debian/rules:95: build] Error 2

Do you have some workaround ?

**Comment by mutability** [comment]
What distribution version exactly?

**Comment by dav2712** [comment]
Sorry for this lack of information. 
I got this issue on latest following distributions (fresh install) : 
- Ubuntu 20.04 (Desktop)
- Kali 2020.1 (Desktop)
- Debian 10.03 (Desktop)
For these 3 distributions I have got the same issue. 

I finally "solved" my issue by installing Ubuntu 18.04.4.

**Comment by LLPP65** [comment]
I found the same running Ubuntu 20.04 on a Raspberry pi. There is no "pyvenv" binary, so I changed the "package-focal/debian/rules" file:

setup_venv:
    #pyvenv $(VENV) --without-pip
    python3 -m venv $(VENV) --without-pip

After that it ran ok and created the .deb file.

**Comment by mutability** [comment]
I can believe this is a problem for Ubuntu/Kali since they're typically picking up packages from unstable and I don't generally test against unstable; I guess something has changed there.

I do not understand the OP having problems on vanilla Buster though. There is a build-dep on python3-venv and python3-venv definitely provides /usr/bin/pyvenv: https://packages.debian.org/buster/amd64/python3-venv/filelist
And our standard build is against Raspbian Buster and it's fine.

@dav2712, can you confirm what architecture & install image you're seeing the problem on with Debian 10, and can you check that `python3-venv` is installed?

**Comment by dav2712** [comment]
I tested again. This works correclty on Debian 10.3. I have missed something the first time. Sorry for that. 
But for Ubuntu 20 and Kali 2020 : The correction provided by @LLPP65 is working fine.

**Comment by mutability** [comment]
Ok, thanks for confirming. I think running it as a module should be fine on Buster too so I'll just switch the buster build over to do that.
