### ISSUE TITLE
Debian 10 / Buster dependency issue: tcl-tls

### ISSUE THREAD

**Issue by bctrainers** [flightaware/piaware_builder#16]
Hi, at line 11 in the control file, the package `tcl-tls` will fail to meet the requirements of version `1.7.16-1+fa1`. Removing `-1+fa1` from the string resolves this particular issue for Debian 10 installations. The package from the stock apt repo for `tcl-tls` has not had any issues or conflicts with Flight Aware on an amd64 build of FlightAware.

https://github.com/flightaware/piaware_builder/blob/6f70ee3d088e939ce7fd48fe22ed5b4601fbeb4a/buster/control#L11

The line will then look like this:

```
Depends: ${shlibs:Depends}, ${misc:Depends}, net-tools, iproute2, tclx8.4, tcl8.6, tcllib, tcl-tls (>= 1.7.16), itcl3
```

```
root@vm-adsb:/var/cache/piaware# apt show tcl-tls
Package: tcl-tls
Version: 1.7.16-1
Priority: optional
Section: interpreters
Source: tcltls
Maintainer: Debian Tcl/Tk Packagers <pkg-tcltk-devel@lists.alioth.debian.org>
Installed-Size: 167 kB
Provides: tcltls
Depends: libc6 (>= 2.14), libssl1.1 (>= 1.1.0), libtcl8.6 (>= 8.6.0-2) | libtcl
Conflicts: libtls0, tcltls
Replaces: libtls0, tcltls
Homepage: https://core.tcl.tk/tcltls
Tag: protocol::ssl, role::shared-lib
Download-Size: 69.8 kB
APT-Manual-Installed: yes
APT-Sources: http://deb.debian.org/debian buster/main amd64 Packages
Description: TLS OpenSSL extension to Tcl
 This package enables communication over SSL-encrypted channels in Tcl.
 .
 Both client and server-side sockets are possible. Additionally, full filevent semantics should be intact.

```

**Comment by mutability** [comment]
Has the upstream Debian package included the build fix that the FA package
provides? Without that tcl-tls will unpredictably hang the whole process.

**Comment by mutability** [comment]
specifically, see the README in https://github.com/flightaware/tcltls-rebuild

**Comment by bctrainers** [comment]
After reading the bug report/ticket listed: 

> We have a process that handles a TLS socket and on EOF or error, it exits.

I have not personally come across this condition on Debian 10 or Debian 9 installations with this particular issue using tcl-tls while feeding data to a multitude of different MLAT/ADSB services. It's possible another bug fix passively fixed the issue originally reported?

Would you happen to have a method to force this errant condition to occur? The backtrace given on that original report seems to be on FreeBSD, on different package versions. So it's possible things have changed since the initial report in Sept 2017.

Locally, I have the following...

```bash
root@vm-adsb:~# openssl version
OpenSSL 1.1.1d  10 Sep 2019
```

```bash
root@vm-adsb:/etc# apt show tcl
Package: tcl
Version: 8.6.9+1
Priority: optional
Section: interpreters
Source: tcltk-defaults
Maintainer: Debian Tcl/Tk Packagers <pkg-tcltk-devel@lists.alioth.debian.org>
Installed-Size: 22.5 kB
Provides: tclsh
Depends: tcl8.6 (>= 8.6.9+dfsg-2)
Breaks: tcl8.3 (<< 8.3.5-15), tcl8.4 (<< 8.4.20-2), tcl8.5 (<< 8.5.14-3), tcl8.6 (<< 8.6.0-2)
Tag: devel::lang:tcl, role::metapackage
Download-Size: 5,636 B
APT-Manual-Installed: yes
APT-Sources: http://deb.debian.org/debian buster/main amd64 Packages
```


```bash
root@vm-adsb:/etc# apt show tcl-tls
Package: tcl-tls
Version: 1.7.16-1
Priority: optional
Section: interpreters
Source: tcltls
Maintainer: Debian Tcl/Tk Packagers <pkg-tcltk-devel@lists.alioth.debian.org>
Installed-Size: 167 kB
Provides: tcltls
Depends: libc6 (>= 2.14), libssl1.1 (>= 1.1.0), libtcl8.6 (>= 8.6.0-2) | libtcl
Conflicts: libtls0, tcltls
Replaces: libtls0, tcltls
Homepage: https://core.tcl.tk/tcltls
Tag: protocol::ssl, role::shared-lib
Download-Size: 69.8 kB
APT-Manual-Installed: yes
APT-Sources: http://deb.debian.org/debian buster/main amd64 Packages
```

```bash
root@vm-adsb:/etc# cat os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by mutability** [comment]
The problem is more general than the specific case in the bug report. We first saw it on the server side on FreeBSD during process close, but it also later affected us on Linux servers. It's not only on process shutdown. And it's been seen in the wild on piaware installs and also on some parallel FlightFeeder client-side management infrastructure that uses tcltls for communication.

From memory the triggering conditions are something like:

 * Have enough outgoing data buffered that it's buffered in the tcl stream, rather than only in openssl / TCP buffers
 * Have the underlying connection break
 * Try to flush or close the tcl socket

This is usually rare (much more likely with a flaky internet connection) but it's a catastrophic failure when it does happen: piaware hangs and cannot recover on its own, a SIGKILL is needed; usually it'll go unnoticed until monitoring starts sending emails about the piaware outage.

And with 30k+ feeders even an individually rare failure turns into something that happens regularly.

You can risk it and run with the unfixed version, it's not going to cause any data corruption etc, but be aware of the potential for these random hangs - you will want to put together some monitoring to notice that piaware has hung somehow.

This definitely still affected 1.7.16 and Debian buster is still on the same package version so I don't see any evidence that it's been fixed in the meantime; I'm not willing to change the dependency without seeing that it's been fixed.

**Comment by bctrainers** [comment]
Fully understandable, thanks for the explanation. With those details known, I'll keep an eye on my installation with what I have currently. If things go sideways, I'll swap over to the tcltls fa package.
