### ISSUE TITLE
issue with 'run-apt-get' prevents upgrade from 5.0 to 6.1 from completing

### ISSUE THREAD

**Issue by profporridge** [flightaware/piaware_builder#18]
I ran into an issue when trying to upgrade via the adsb stats page. It seems to be related to the 'run-apt-get' code. The command ```sudo apt-get update``` was failing when run in a terminal with the error ``` Repository 'http://archive.raspberrypi.org/debian buster InRelease' changed its 'Suite' value from 'testing' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.```

Solution was to run ```sudo apt-get update --allow-releaseinfo-change``` in a terminal. After this I was able to update successfully from the adsb stats page.

**Comment by profporridge** [comment]
This was encountered on a custom install. 
````pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Comment by profporridge** [comment]
This issue was submitted to the wrong project. Will re-create it in https://github.com/flightaware/piaware

**Comment by mutability** [comment]
Here's fine.

This is a problem with the upstream apt infrastructure that we can't do anything about. Older Buster releases included an apt version that requires user interaction to accept this change. Subsequently, there was a fix made to the Buster version to avoid this, but if you had not taken that upgrade before the release of Bullseye, you'll hit this issue. 

It can be avoided by passing the right config options to apt, but this isn't possible for existing installs out there as we need to push a package upgrade to pass the right config options, and that's not possible for installs that break on upgrade attempts. It shouldn't be a problem in the future since newer apt versions default to the fixed behavior without additional options.

The FlightAware buster mirror is frozen at an old version for now (before the change in Suite value) to mitigate exactly this problem, but you're not using that mirror.
