### ISSUE TITLE
/etc/cron.daily/logrotate: error: piaware:2 extra arguments for create

### ISSUE THREAD

**Issue by boozedog** [flightaware/piaware_builder#8]
I've been getting this error daily since 10 Dec:

```
/etc/cron.daily/logrotate:
error: piaware:2 extra arguments for create
error: found error in /var/log/piaware.log , skipping
```

I'm running Rapbian 8 (jessie).

**Comment by mutability** [comment]
/etc/logrotate.d/piaware (as shipped) has no "create" option, so I guess that either you have a modified config file or another config file is interfering.

**Comment by boozedog** [comment]
My /etc/logrotate.d/piaware matches the one found here: https://github.com/flightaware/piaware_builder/blob/c13903729700871d72fbeaf370b77a8e97ae6a57/wheezy/piaware.logrotate

I see following on line two:
```create piaware root 0644```

I think that's the line that Raspbian is complaining about.

**Comment by boozedog** [comment]
Hmmm how did I end up with wheezy version of that file on a jessie system?

**Comment by mutability** [comment]
Aha, wheezy, ok. Let me look.

**Comment by mutability** [comment]
If you have autoupdates enabled then there would have been an autoupgrade from 2.1 to 3.1 done in december; this will install the wheezy package regardless of target distribution, which generally works OK on a jessie system too but I guess the logrotate rule doesn't work.

If you do another piaware update it will get the jessie version (the wheezy version is only installed initially because the 2.1 autoupgrade mechanism doesn't have a way to upgrade using different packages based on the distribution version; 3.x does know about that)

**Comment by boozedog** [comment]
Cool. I'll give that a try.

**Comment by boozedog** [comment]
OK I just updated to latest piaware using steps 2 and 3 from this page: http://flightaware.com/adsb/piaware/install

Confirmed that autoupgrade was already turned on.

Looks like /etc/logrotate.d/piaware is fixed now!

**Comment by mutability** [comment]
OK, great. I will have a look at the wheezy config file and see if I can get it working on both wheezy and jessie
